from dotenv import load_dotenv
import os

load_dotenv()

AIRTABLE_PAT = (os.getenv("AIRTABLE_PAT")) #-> str: #initalizes personal access token
AIRTABLE_TEST_BASE_ID = "appr8SepSgx9SP6ir" #-> str: intializes base id
######-> str: initalizes individual tables 
AIRTABLE_TEST_CONTACTS = "tblXBR1YTXYvGhwWJ"
AIRTABLE_TEST_EMPLOYEESandVOLUNTEERS = "tblk3Qd3sKV9JPNtx"
AIRTABLE_TEST_SERVICE = "tbl2hG3F6LlSW3Bm7"
AIRTABLE_TEST_BIKESforSALE = "tblWAo0tdOEFN2RaA"
AIRTABLE_TEST_BIKESforDONO = "tblGlO7tDFuQg3RKy"
AIRTABLE_TEST_RENTAL_BIKES = "tbllDlYHfpxvWi5XH"
AIRTABE_TEST_WEBSHOP_INQUIRY = "tblaKhFw5X6cvBNNp"
AIRTABLE_TEST_SALES_ORDERS = "tblp14q73VINEXGM1"
AIRTABLE_TEST_ORDER_ITEMS = "tblCKoA3zEjflGoLf"
AIRTABLE_TEST_INTERACTIONS = "tblYDL11X6PuvlnKA"
AIRTABLE_TEST_NO_LONGER_USER_SALES = "tbldLNHp78lSBKaxZ"
AIRTABLE_TEST_RENTAL = "tblATiIu8nRsN9JSW" 
######