from dotenv import load_dotenv
import os

load_dotenv()

AIRTABLE_PAT = (os.getenv("AIRTABLE_PAT")) #-> str: #initalizes personal access token
AIRTABLE_BASE_ID = "appr8SepSgx9SP6ir"
AIRTABLE_CONTACTS = "tblXBR1YTXYvGhwWJ"
AIRTABLE_EMPLOYEESandVOLUNTEERS = "tblk3Qd3sKV9JPNtx"
AIRTABLE_SERVICE = "tbl2hG3F6LlSW3Bm7"
AIRTABLE_BIKESforSALE = "tblWAo0tdOEFN2RaA"
AIRTABLE_BIKESforDONO = "tblGlO7tDFuQg3RKy"
AIRTABLE_RENTAL_BIKES = "tbllDlYHfpxvWi5XH"
AIRTABE_WEBSHOP_INQUIRY = "tblaKhFw5X6cvBNNp"
AIRTABLE_SALES_ORDERS = "tblp14q73VINEXGM1"
AIRTABLE_ORDER_ITEMS = "tblCKoA3zEjflGoLf"
AIRTABLE_INTERACTIONS = "tblYDL11X6PuvlnKA"
AIRTABLE_NO_LONGER_USER_SALES = "tbldLNHp78lSBKaxZ"
AIRTABLE_RENTAL = "tblATiIu8nRsN9JSW" 